"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create cities, poles, devices, users, results, status events and push tokens."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('launch_offset_m', sa.Double(), nullable=False),
    sa.Column('break_tolerance_m', sa.Double(), nullable=False),
    sa.Column('reference_fiber_length_m', sa.Double(), nullable=True),
    sa.Column('reference_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_state', sa.Enum('AWAITING_REFERENCE', 'OK', 'SUSPECT_BREAK', 'BREAK', name='line_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('device_health', sa.Enum('ONLINE', 'DISCONNECTED', 'FAULT', name='device_health', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('suspect_distance_m', sa.Double(), nullable=True),
    sa.Column('last_result_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("device_health IN ('ONLINE', 'DISCONNECTED', 'FAULT')", name=op.f('ck_cities_device_health')),
    sa.CheckConstraint("line_state IN ('AWAITING_REFERENCE', 'OK', 'SUSPECT_BREAK', 'BREAK')", name=op.f('ck_cities_line_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('name', name=op.f('uq_cities_name'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_rotated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('highest_seq', sa.Integer(), nullable=False),
    sa.Column('last_fault_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_devices_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('api_key_hash', name=op.f('uq_devices_api_key_hash')),
    sa.UniqueConstraint('city_id', name=op.f('uq_devices_city_id'))
    )
    op.create_table('poles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lon', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_poles_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poles')),
    sa.UniqueConstraint('city_id', 'number', name=op.f('uq_poles_city_id_number'))
    )
    with op.batch_alter_table('poles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poles_city_id'), ['city_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('maintainer', 'admin', name='role', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('approval_state', sa.Enum('pending', 'approved', 'rejected', 'disabled', name='approval_state', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('approved_city_id', sa.Integer(), nullable=True),
    sa.Column('requested_city_id', sa.Integer(), nullable=True),
    sa.Column('registration_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("approval_state IN ('pending', 'approved', 'rejected', 'disabled')", name=op.f('ck_users_approval_state')),
    sa.CheckConstraint("role IN ('maintainer', 'admin')", name=op.f('ck_users_role')),
    sa.ForeignKeyConstraint(['approved_city_id'], ['cities.id'], name=op.f('fk_users_approved_city_id_cities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_city_id'], ['cities.id'], name=op.f('fk_users_requested_city_id_cities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('registration_token_hash', name=op.f('uq_users_registration_token_hash'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_approval_state'), ['approval_state'], unique=False)

    op.create_table('push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_push_tokens_token'))
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('result', 'fault', name='result_kind', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_s', sa.Double(), nullable=False),
    sa.Column('backlog', sa.Boolean(), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('end_event_distance_m', sa.Double(), nullable=True),
    sa.Column('fiber_length_m', sa.Double(), nullable=True),
    sa.Column('link_loss_db', sa.Double(), nullable=True),
    sa.Column('otdr_firmware', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('pi_health', sa.JSON(), nullable=True),
    sa.Column('fault_kind', sa.String(length=32), nullable=True),
    sa.Column('fault_detail', sa.Text(), nullable=True),
    sa.Column('fault_status_code', sa.Integer(), nullable=True),
    sa.CheckConstraint("kind IN ('result', 'fault')", name=op.f('ck_results_result_kind')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_results_city_id_cities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_results_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('ix_results_city_id_received_at', ['city_id', 'received_at'], unique=False)
        batch_op.create_index('ix_results_device_id_seq', ['device_id', 'seq'], unique=False)

    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.Enum('line', 'device', name='status_dimension', native_enum=False, create_constraint=False, length=32), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed', sa.Boolean(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("dimension IN ('line', 'device')", name=op.f('ck_status_events_status_dimension')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_status_events_city_id_cities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('fk_status_events_result_id_results'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_events'))
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index('ix_status_events_city_id_occurred_at', ['city_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_status_events_city_id_occurred_at')

    op.drop_table('status_events')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_device_id_seq')
        batch_op.drop_index('ix_results_city_id_received_at')

    op.drop_table('results')
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_user_id'))

    op.drop_table('push_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_approval_state'))

    op.drop_table('users')
    with op.batch_alter_table('poles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poles_city_id'))

    op.drop_table('poles')
    op.drop_table('devices')
    op.drop_table('cities')
    # ### end Alembic commands ###
